# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh
fpath=( ~/.zcomplete "${fpath[@]}" )

ZSH_THEME=""

CASE_SENSITIVE="true"
DISABLE_AUTO_UPDATE="true"
DISABLE_LS_COLORS="false"
DISABLE_AUTO_TITLE="true"
ENABLE_CORRECTION="false"
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
HIST_STAMPS="yyyy-mm-dd"
# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder
plugins=(history git sudo common-aliases colored-man systemd)
source $ZSH/oh-my-zsh.sh

RPROMPT='[%*]'

alias reload=". ~/.zshrc"

ZSH_AUTOSUGGEST_STRATEGY=match_prev_cmd
source ~/.zsh-autosuggestions/zsh-autosuggestions.zsh
#       Ctrl+Space
bindkey '^ ' autosuggest-accept

source ~/.zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

source ~/.profile.d/load
