#!/bin/bash

shopt -s autocd
shopt -s checkwinsize
export HISTFILESIZE=5000
export HISTCONTROL=ignoreboth

#show colored man-pages
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;36m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

if [[ $(which git) ]]; then
	function parse_git_branch {
		if [[ $(git status -s 2>/dev/null) ]]; then
			echo '*'
		fi
		git branch 2>/dev/null | cut -d ' ' -f 2
	}
else
	function parse_git_branch(){
		return 0;
	}
fi

export PS1="\[\e[00;37m\]\$? \[\e[0m\]\[\e[01;33m\]\u\[\e[0m\]\[\e[01;31m\]@\[\e[0m\]\[\e[01;34m\]\h\[\e[0m\]\[\e[00;37m\]:\[\e[0m\]\[\e[01;32m\]\w\[\e[0m\]\[\e[00;37m\]\n\[\e[0m\]\[\e[01;32m\]\A\[\e[0m\]\[\e[00;37m\] \[\e[01;31m\]\$(parse_git_branch | tr -d '\n')\[\e[0m\] \[\e[00;37m\]\# \[\e[0m\]\\$> "
export PS2='2nd> '
export PS3='3rd> '
export PS4='4th> '

alias reload=". ~/.bashrc"

source ~/.profile.d/load
