#!/bin/bash

#source other scripts
#source /usr/share/doc/pkgfile/command-not-found.bash
[ -r /etc/profile.d/cnf.sh ] && . /etc/profile.d/cnf.sh

PATH=$HOME/bin:$HOME/.gem/ruby/2.0.0/bin:$PATH

shopt -s autocd
export HISTFILESIZE=5000
export HISTCONTROL=ignoreboth
export EDITOR=vim
export VISUAL=vim

#show colored man-pages
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;36m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

#alias definitions
alias chmox="chmod +x"
alias cd..="cd .."
alias ddd="killall -USR1 dd"
alias sddd="sudo killall -USR1 dd"
#auto color for specified commands
alias l="ls --color=auto"
alias ls="ls --color=auto"
alias ll="ls --color=auto -l"
alias lr="ls --color=auto -r"
alias lla="ls --color=auto -la"
alias grep='grep --color=auto'

alias killlall="killall"
alias kilall="killall"
alias kilal="killall"
alias killlal="killall"

alias quit="exit"

alias wget='wget --content-disposition'
alias vim="vim -p"
alias vi="vim -p"

#END alias-definitions

alias pwedit="vim -p /etc/{passwd,group,shadow,gshadow}"
alias pitime='time echo "scale=1000; 4*a(1)" | bc -l > /dev/null'
alias cmdlist='find $(echo $PATH | tr ":" "\n")'
alias makepasswd='makepasswd --minchars=10 --maxchars=25 --count=10'
alias upd_linux="mount -o remount,rw /boot && pacman -Syu && mount -o remount,ro /boot && mount | grep ^/dev/vda1"
alias reload=". ~/.bashrc"
alias snet='ip addr | \grep -v "inet6" | \grep inet | cut -d " " -f 6 | \grep -v 127.0.0.1/8 | xargs nmap -sP'

#correct some fast tipped cds
function c {
	if [ $1 == "d.." ]; then
		cd ..;
		pwd;
	fi
	if [ -d $1 ]; then
		cd $1;
		pwd;
	fi
	return 0;
}

#The function will find the given user and search for a mysql-password in its
#Home-direcotory, which will get printed out!
#arg1: user where to find a config-file
#      if not given, it uses the current user in the $HOME and $USER-Variable
function mysqlpw() {
	if [[ -z $1 ]]; then
		H=$HOME
		U=$USER
		elif [[ `id $1` ]]; then
			U=$1;
			H=$(grep ^${1}: /etc/passwd | cut -d":" -f 6);
		else 
			return 1;
	fi;

	echo MySQL-Password for user $U is $(grep "password=" $H/.my.cnf | cut -d"=" -f 2);
}

#read $HOME/.bash.d
for file in $HOME/.bash.d/*.sh 
do
	if [ -x $file ]
		then
		source $file
	fi
done
unset file

if [[ `which git` ]]; then
	function parse_git_dirty {
		[[ $(git status 2> /dev/null | tail -n1) != "nothing to commit (working directory clean)" ]] && echo "*"
		}
	function parse_git_branch {
		git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/[\1$(parse_git_dirty)]/"
	}
else
	function parse_git_branch(){
		return 0;
	}
fi
export PS1="\[\e[00;37m\]\$? \[\e[0m\]\[\e[01;33m\]\u\[\e[0m\]\[\e[01;31m\]@\[\e[0m\]\[\e[01;34m\]\h\[\e[0m\]\[\e[00;37m\]:\[\e[0m\]\[\e[01;32m\]\w\[\e[0m\]\[\e[00;37m\]\n\[\e[0m\]\[\e[01;32m\]\A\[\e[0m\]\[\e[00;37m\] \\$> \[\e[0m\]"
#export PS1='\[\033[0m\]$(if [ $? != 0 ]; then echo "\[\033[0;1;31m\]"; else echo "\[\033[0;32m\]"; fi)[$(if [ $UID == 0 ]; then echo "\[\033[41m\]"; fi)\u\[\033[49m\]@\h:\W$(parse_git_branch)]\[\033[0m\] \#\$ '
export PS2='2nd> '
export PS3='3rd> '
export PS4='4th> '

#read $HOME/.bash.d
for file in $HOME/.bash.d/*.sh 
do
	if [ -x $file ]
		then
		source $file
	fi
done
unset file