#!/bin/bash

shopt -s autocd
shopt -s checkwinsize
export HISTFILESIZE=5000
export HISTCONTROL=ignoreboth

#show colored man-pages
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;36m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

# Liquidprompt #

# if you change settings of liquidprompt, change settings in zshrc, too

#LP_ENABLE_RUNTIME=1
LP_ENABLE_TITLE=1
LP_ENABLE_SSH_COLORS=1
LP_ENABLE_VCS_ROOT=1
LP_DISABLED_VCS_PATH=""
LP_ENABLE_TEMP=0
# if in git folder, the prompt takes very long to rebuild
mountpoint $HOME 2> /dev/null > /dev/null && LP_DISABLED_VCS_PATH="$HOME"
source ~/.liquidprompt/liquidprompt
RPROMPT='[%*]'

# Liquidprompt END #

alias reload=". ~/.bashrc"

source ~/.profile.d/load
